import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
df = pd.read_csv("results_log.csv")
plt.subplot(4, 4, 1)
plt.plot(df['WaveLength'], df['r01none'], label='r01none')
plt.legend()
plt.subplot(4, 4, 2)
plt.plot(df['WaveLength'], df['r01big'], label='r01big')
plt.legend()
plt.subplot(4, 4, 3)
plt.plot(df['WaveLength'], df['r01mid'], label='r01mid')
plt.legend()
plt.subplot(4, 4, 4)
plt.plot(df['WaveLength'], df['r01small'], label='r01small')
plt.legend()
plt.subplot(4, 4, 5)
plt.plot(df['WaveLength'], df['r005none'], label='r005none')
plt.legend()
plt.subplot(4, 4, 6)
plt.plot(df['WaveLength'], df['r005big'], label='r005big')
plt.legend()
plt.subplot(4, 4, 7)
plt.plot(df['WaveLength'], df['r005mid'], label='r005mid')
plt.legend()
plt.subplot(4, 4, 8)
plt.plot(df['WaveLength'], df['r005small'], label='r005small')
plt.legend()
plt.subplot(4, 4, 9)
plt.plot(df['WaveLength'], df['y01none'], label='y01none')
plt.legend()
plt.subplot(4, 4, 10)
plt.plot(df['WaveLength'], df['y01big'], label='y01big')
plt.legend()
plt.subplot(4, 4, 11)
plt.plot(df['WaveLength'], df['y01mid'], label='y01mid')
plt.legend()
plt.subplot(4, 4, 12)
plt.plot(df['WaveLength'], df['y01small'], label='y01small')
plt.legend()
plt.subplot(4, 4, 13)
plt.plot(df['WaveLength'], df['y005none'], label='y005none')
plt.legend()
plt.subplot(4, 4, 14)
plt.plot(df['WaveLength'], df['y005big'], label='y005big')
plt.legend()
plt.subplot(4, 4, 15)
plt.plot(df['WaveLength'], df['y005mid'], label='y005mid')
plt.legend()
plt.subplot(4, 4, 16)
plt.plot(df['WaveLength'], df['y005small'], label='y005small')
plt.legend()
plt.show()
print(df)
